host-address: 192.168.128.202
registry-port: 8081
team-name: ettMinutt

kafka:
  port: 29092
  immigrant:
    consumer:
      topic: itverket-immigration-3
      ip-address: ${host-address}
      port: ${kafka.port}
      group-id: ${team-name}
  immigration-result:
    producer:
      topic: itverket-immigration-result
      ip-address: ${host-address}
      port: ${kafka.port}
      clientId: ${team-name}
      acks-config: all