host-address: 10.14.5.160
registry-port: 8081
team-name: placeholder

kafka:
  port: 29092
  immigrant:
    consumer:
      topic: itverket-immigration-0
      ip-address: ${host-address}
      port: ${kafka.port}
      group-id: ${team-name}
  immigration-result:
    producer:
      topic: itverket-immigration-result
      ip-address: ${host-address}
      port: ${kafka.port}
      clientId: ${team-name}
      acks-config: all